# Generated by Django 2.2.12 on 2020-04-22 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200422_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 4, 22, 4, 8, 33, 908981), verbose_name='Опубликовано'),
        ),
    ]
