# Generated by Django 2.2.12 on 2020-12-23 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201222_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 23, 4, 23, 21, 723636), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 23, 4, 23, 21, 723636), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItems',
        ),
    ]
